### ISSUE TITLE
graphic + unfinished functions = no game screen...

### ISSUE THREAD

**Issue by destroyer9** [eee-c/ice-code-editor#103]
ive been using 3d game programming for kids and when i haven't finished a function the game won't show up. i mean, what if i wanna check something thats off the screen??? you get what i mean???

**Comment by batasrki** [comment]
Can you give us more details, including a code sample, please?

**Comment by eee-c** [comment]
The best option in this case is to uncheck the box in the `Update` button. This will disable the auto-update of the code on the game screen.

You'll have to click the button every time that you want changes to show up on the game screen in this case. You can re-check the box when you want to resume the usual behavior.
