### ISSUE TITLE
Loading 

### ISSUE THREAD

**Issue by SharonD19** [eee-c/ice-code-editor#143]
I have been working on the ICE coder.  gamingjs.com and it will not load or refresh.  It has been frozen for two days.  I am using the 3D Game Programming for Kids, Create Interactive Worlds with JavaScript.  I am using google chrome and a windows machine. 

Please let me know what can be done to get this programming working again.

Thank you

**Comment by eee-c** [comment]
Hi! So sorry for the trouble, but I think we can get you sorted out.

You've likely added some code that locked the browser. That's surprisingly easy to do. So easy, in fact, that we added a special "edit only" mode to the ICE editor. To access this mode, add `?e` to the URL that you use to visit the editor:

http://gamingjs.com/ice/?e

In edit-only mode, you'll be able to change your code, but it won't try to run it -- so it won't lock the browser. Once you are in edit-only mode, you'll have to remove the last bit of code that you typed in. After that, remove the `?e` from the URL, hit `<Enter>` to reload the editor and, hopefully, the problem will be resolved.

Based on the URL that you're using, you've got the first edition of the book. I don't have a copy of that handy, but I believe that edit-only mode is described in more detail in chapter two of that edition. 

If you have further questions, about edit-only mode or any code, please use the forums for the latest edition of the book: https://talk.code3dgames.com/. It's easier for me to keep track of things over there.

Hope that helps,

-Chris

**Comment by SharonD19** [comment]
Thank you.
